FROM node:14.20.0 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 4200

# CMD ["npm", "start"]
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]
