export class Constants {
    // PERMISSIONS
    public static MONITOR_LOG_AND_FLOW_CARD = 'MONITOR_LOG_AND_FLOW_CARD';
    public static SERVICE_LOG = 'SERVICE_LOG';
    public static EVENT_LOG = 'EVENT_LOG';
    public static APPLICATION_LOG = 'APPLICATION_LOG';
    public static SYSTEM_STATUS = 'SYSTEM_STATUS';
    public static FLOW_INPUT = 'FLOW_INPUT';
    public static FLOW_MONITORING = 'FLOW_MONITORING';
    public static FLOW_CARD = 'FLOW_CARD';
    public static LOG_CARD = 'LOG_CARD';
    public static USER_MANAGEMENT_CARD = 'USER_MANAGEMENT_CARD';
    public static WORKSPACE_MANAGEMENT_CARD = 'WORKSPACE_MANAGEMENT_CARD';
    public static BUSSINESS_MANAGEMENT_CARD = 'BUSSINESS_MANAGEMENT_CARD';
    public static CUD_ACTIVITY_TYPE_AND_ACTIVITY_MODEL = 'CUD_ACTIVITY_TYPE_AND_ACTIVITY_MODEL';
    public static CUD_FLOW_TYPE_AND_FLOW_MODEL = 'CUD_FLOW_TYPE_AND_FLOW_MODEL';
    public static ENABLED_DISALED_FLOWS = 'ENABLED_DISALED_FLOWS';
    public static APP_SERVICE_MANAGEMENT_CARD = 'APP_SERVICE_MANAGEMENT_CARD';
    public static WEB_SERVICE_MANAGEMENT_CARD = 'WEB_SERVICE_MANAGEMENT_CARD';
    public static WEB_SERVICE_MANAGEMENT_CURD_ACCESS = 'WEB_SERVICE_MANAGEMENT_CURD_ACCESS';
    public static WEB_SERVICE_MANAGEMENT_ENABLE_DISABLE_ACCESS = 'WEB_SERVICE_MANAGEMENT_ENABLE_DISABLE_ACCESS';
    public static TASK_MANAGEMENT_CARD = 'TASK_MANAGEMENT_CARD';
    public static TASK_MANAGEMENT_ACTIONS = 'TASK_MANAGEMENT_ACTIONS';
    public static APPLICATION_INTEGRATION_CARD = 'APPLICATION_INTEGRATION_CARD';
    public static CONFIGURATION_CARD = 'CONFIGURATION_CARD';
    public static APPLICATION_PARAMETER_CURD_ACCESS = 'APPLICATION_PARAMETER_CURD_ACCESS';
    public static TOOLS_CARD = 'TOOLS_CARD';
    public static TOOLS_IMPORT_EXPORT_WORKSPACE_ITEMS = 'TOOLS_IMPORT_EXPORT_WORKSPACE_ITEMS';
    public static TOOLS_REINDEXING = 'TOOLS_REINDEXING';
    public static DEVELOPMENT_CARD = 'DEVELOPMENT_CARD';
    public static DEV_BREAK_LOCK_ON_TEMPLATE_AND_SYSTEM_LIBRARY = 'DEV_BREAK_LOCK_ON_TEMPLATE_AND_SYSTEM_LIBRARY';
    public static DEV_BREAK_LOCK_ON_USER_SCRIPT = 'DEV_BREAK_LOCK_ON_USER_SCRIPT';
    public static DEV_CRUD_USER_SCRIPT = 'DEV_CRUD_USER_SCRIPT';
    public static DEV_CRUD_TEMPLATE = 'DEV_CRUD_TEMPLATE';
    public static DEV_CRUD_SYSTEM_LIBRARY = 'DEV_CRUD_SYSTEM_LIBRARY';
    public static DEV_IMPORT_EXPORT_TEMPLATE_AND_SYSTEM_LIBRARY = 'DEV_IMPORT_EXPORT_TEMPLATE_AND_SYSTEM_LIBRARY';
    public static DEV_IMPORT_EXPORT_USER_SCRIPT = 'DEV_IMPORT_EXPORT_USER_SCRIPT';
    public static ARCHIVE_CARD = 'ARCHIVE_CARD';
    public static PROCESSING_OVERVIEW_CARD = 'PROCESSING_OVERVIEW_CARD';
    public static PROCESSING_OVERVIEW_WEB_SERVICE = 'PROCESSING_OVERVIEW_WEB_SERVICE';
    public static PROCESSING_OVERVIEW_PROCESS_ENGINE = 'PROCESSING_OVERVIEW_PROCESS_ENGINE';
    public static PROCESSING_OVERVIEW_SERVER_QUEUE = 'PROCESSING_OVERVIEW_SERVER_QUEUE';
    public static PROCESSING_OVERVIEW_SERVER_TASK_CACHE = 'PROCESSING_OVERVIEW_SERVER_TASK_CACHE';
    public static PROCESSING_OVERVIEW_SERVER_ITEM_CACHE = 'PROCESSING_OVERVIEW_SERVER_ITEM_CACHE';
    
    public static USER_MANAGEMENT_CRUD = 'USER_MANAGEMENT_CRUD';
    public static WORKSPACE_MANAGEMENT_CRUD = 'WORKSPACE_MANAGEMENT_CRUD';
    public static DEPLOY_UNDEPLOY_WORKSPACE = 'DEPLOY_UNDEPLOY_WORKSPACE';
    public static BUSSINESS_MANAGEMENT_CRUD_FLOW_AND_FLOW_GROUP = 'BUSSINESS_MANAGEMENT_CRUD_FLOW_AND_FLOW_GROUP';
    public static ENABLE_DISABLE_SCHEDULERS = 'ENABLE_DISABLE_SCHEDULERS';
    public static ENABLE_DISABLE_SERVICES = 'ENABLE_DISABLE_SERVICES';
    public static CONFIGURATION_OF_SEVER = 'CONFIGURATION_OF_SEVER';
    public static CONFIGURATION_SCRIPT_ENGINE_AND_GROUP = 'CONFIGURATION_SCRIPT_ENGINE_AND_GROUP';
    public static CONFIGURATION_LOG_MAINTENANCE = 'CONFIGURATION_LOG_MAINTENANCE';
    public static IMPORT_EXPORT_USER_SCRIPT = 'IMPORT_EXPORT_USER_SCRIPT';
    public static BREAK_LOCK_ON_USER_SCRIPT = 'BREAK_LOCK_ON_USER_SCRIPT';
    public static CREATE_UPDATE_DELETE_OF_NETUSER_RESOURCES_WITH_TEST_FEATURE = 'CREATE_UPDATE_DELETE_OF_NETUSER_RESOURCES_WITH_TEST_FEATURE';

    public static USERNAME = 'USERNAME';
    public static SOURCE = 'source';
    public static WORKSPACE_ID = 'workspaceId';
    public static CURRENTUSER = 'currentUser';
    public static LOGIN_PAGE_URL = '/login';
    public static INVALID_URL = 'INVALID_URL';

    // Task Management
    public static RECORDS_PER_PAGE = 50;

    // Import 2.x
    public static TEIS_ITEM_TYPE = 'PROCESS';

    // Application Integration
    public static SEARCH_LOG_DAYS = 7;
    public static SEARCH_LOG_HOURS = 0;
    public static SEARCH_LOG_MINUTES = 0;
    public static SEARCH_LOG_SECONDS = 0;
    public static BREAK_PIT_LOCK = 'BREAK_PIT_LOCK';
    public static CREATE_UPDATE_DELETE_GLOBAL_PARAMS = 'CREATE_UPDATE_DELETE_GLOBAL_PARAMS';
    public static CREATE_UPDATE_DELETE_NETUSER_WITH_TEST = 'CREATE_UPDATE_DELETE_NETUSER_WITH_TEST';
    // public static CREATE_UPDATE_DELETE_COPY_PASTE_FPIT = 'CREATE_UPDATE_DELETE_COPY_PASTE_FPIT';
    public static DEPLOY_UNDEPLOY_FPIT = 'DEPLOY_UNDEPLOY_FPIT';
    public static OPEN_UPDATE_WORKSPACE = 'OPEN_UPDATE_WORKSPACE';
    public static RESTRUCTURING_VIEW = 'RESTRUCTURING_VIEW';
    public static START_STOP_REMOVE_ERROR_FLAG_PIT = 'START_STOP_REMOVE_ERROR_FLAG_PIT';

}
